version: '2'
services:
    fexco_eircode-app:
        image: fexco_eircode
        external_links:
            - fexco_eircode-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fexco_eircode?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fexco_eircode-mysql:
        extends:
            file: mysql.yml
            service: fexco_eircode-mysql
