version: '2'
services:
    fexco_postcode-mongodb:
        container_name: fexco_postcode-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/FEXCO_postcode/mongodb/:/data/db/
